version: '3'

volumes:
  mysql-volume:

services:
  front:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./front/:/var/www/html
    ports:
      - 8080:8080
    command: "npm run serve"
    tty: true

  server:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./server/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=attend_log
      - DB_USERNAME=attend_log
      - DB_PASSWORD=password
      - "TZ=Asia/Tokyo"
    tty: true

  api:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - ./server/:/var/www/html
    tty: true

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: attend_log
      MYSQL_USER: attend_log
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
    tty: true