version: '3'

volumes:
  mysql-volume:

services:
  front:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./front/:/var/www/html
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    command: "npm run serve"
    tty: true

  server:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./server/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=attend_log
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - "TZ=Asia/Tokyo"
    tty: true

  api:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - server
    volumes:
      - ./server/:/var/www/html
    tty: true

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: attend_log
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
    tty: true