name: ServerCi

on: [push]

jobs:
  phpunit:
    name: phpunit

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: docker-compose down
      run: |
        docker-compose down -v
    - name: docker-compose up
      run: |
        docker-compose up -d --build server db
      env:
        MYSQL_DATABASE: attend_log
        MYSQL_USER: attend_log
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
        TZ: 'Asia/Tokyo'
    - name: Install dependencies
      run: |
        docker-compose exec -T server bash -c "composer install --prefer-dist --no-progress --no-suggest"
    - name: create database file
      run: |
        docker-compose exec -T server bash -c "mkdir -p database"
        docker-compose exec -T server bash -c "touch testing.sqlite"
    - name: migrate
      run: |
        docker-compose exec -T server bash -c "php artisan migrate --env=testing"
    - name: Run test
      run: |
        docker-compose exec -T server bash -c "composer test"