name: ServerCi

on: [push]

jobs:
  phpunit:
    name: phpunit

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create dot env file
      shell: bash
      run: |
        touch .env
        echo "WEB_PORT=${{ secrets.WEB_PORT }}" >> .env
        echo "API_PORT=${{ secrets.API_PORT }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> .env
    - name: docker-compose up
      run: |
        docker-compose up -d --build server db
    - name: Install dependencies
      run: |
        docker-compose exec -T server bash -c "composer install --prefer-dist --no-progress --no-suggest"
    - name: docker-compose ps
      run: |
        docker-compose ps
    - name: create database file
      run: |
        docker-compose exec -T server bash -c "mkdir -p database"
        docker-compose exec -T server bash -c "touch testing.sqlite"
    - name: migrate
      run: |
        docker-compose exec -T server bash -c "php artisan migrate --env=testing"
    - name: Run test
      run: |
        docker-compose exec -T server bash -c "composer test"