name: ServerCi

on: [push]

jobs:
  phpunit:
    name: phpunit

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: docker-compose down
      run: |
        docker-compose down -v
    - name: docker-compose up
      run: |
        docker-compose up -d --build server db
    - name: Install dependencies
      run: |
        docker-compose exec -T server bash -c "composer install --prefer-dist --no-progress --no-suggest"
        docker-compose exec -T server bash -c "composer dump-autoload"
        docker-compose exec -T server bash -c "php artisan config:clear"
    - name: create database file
      run: |
        docker-compose exec -T server bash -c "mkdir -p database"
        docker-compose exec -T server bash -c "touch database/testing.sqlite"
    - name: Run test
      run: |
        docker-compose exec -T server bash -c "composer test"