name: ServerCi

on: [push]

jobs:
  phpunit:
    name: phpunit

    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        ports:
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: attend_log
          MYSQL_ROOT_PASSWORD: root
          TZ: 'Asia/Tokyo'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create dot env file
      shell: bash
      run: |
        touch .env
        echo "WEB_PORT=${{ secrets.WEB_PORT }}" >> .env
        echo "API_PORT=${{ secrets.API_PORT }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> .env
    - name: docker-compose up
      run: |
        docker-compose up -d
    - name: Install dependencies
      run: |
        docker-compose exec -T server bash -c "composer install --prefer-dist --no-progress --no-suggest"
    - name: Run test suite
      run: |
        docker-compose exec -T server bash -c "cp .env.example .env"
        docker-compose exec -T server bash -c "composer run-script test"