name: ServerCi

on: [push]

jobs:
  phpunit:
    name: phpunit

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: dokcer-compose up
      run: |
        docker-compose up -d
    - name: Install dependencies
      run: |
        docker-compose exec -T server bash -c "composer install --prefer-dist --no-progress --no-suggest"
    - name: Run test suite
      run: |
        docker-compose exec -T server bash -c "composer run-script test"